server:
  # 服务端口
  port: 8092

# dubbo相关配置
dubbo:
  # dubbo注册中心相关配置
  registry:
    # 连接注册中心超时时间【单位毫秒】
    timeout: 3000
    # 注册中心地址，格式：协议://IP地址:端口号
    address: nacos://127.0.0.1:8848
    # 所在的命名空间
    group: dubbo-boot
    parameters:
      username: nacos
      password: nacos
  # 协议的相关配置
  protocol:
    # 使用的协议的名称
    name: dubbo
    # 使用的传输端口，默认是20880【设置-1表示使用随机端口】
    port: -1
    # 序列化使用的协议
    serialization: hessian2
  # 消费者相关配置
  consumer:
    # 消费者调用超时时间
    timeout: 3000
